# Basic settings
name: Jonathan Poltak Samosir's Blog
timezone: Asia/Jakarta
encoding: utf-8

# Plugins
gems:
  - jekyll-sitemap

# Conversion
markdown: kramdown
highlighter: rouge

# Serving
detach: false
port: 4000
host: 127.0.0.1
incremental: true

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "posts"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "pages"

exclude: [
          docs/,
          lib/,
          scripts/,
          search.json,
          Gemfile,
          Gemfile.lock,
          package.json,
          README.markdown,
          yarn.lock,
          gulpfile.js
         ]
include: [
          .htaccess
         ]

navbar: true

permalink: pretty
