name: Jonathan Poltak Samosir's Blog


# Conversion
markdown: kramdown
highlighter: rouge

# Serving
detach: false
port: 4000
host: 127.0.0.1

timezone: Australia/Melbourne
encoding: utf-8

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "posts"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "pages"

exclude: [
          docs/,
          lib/,
          scripts/
         ]
include: [
          .htaccess
         ]

navbar: true

permalink: pretty
