# Basic settings
name: Jonathan Poltak Samosir's Blog
timezone: Asia/Jakarta
encoding: utf-8

# Meta info
title: Jonathan Poltak Samosir's Blog
description: A small personal site and blog
author: poltak_
twitter:
username: poltak_
social:
name: Jonathan Poltak Samosir
links:
  - https://github.com/poltak
  - https://twitter.com/poltak_
  - https://www.linkedin.com/in/jsamosir

# Plugins
gems:
  - jekyll-sitemap
  - jekyll-seo-tag

# Conversion
markdown: kramdown
highlighter: rouge

# Serving
detach: false
port: 4000
host: 127.0.0.1
incremental: true

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "posts"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "pages"

exclude: [
          docs/,
          lib/,
          scripts/,
          node_modules/,
          search.json,
          Gemfile,
          Gemfile.lock,
          package.json,
          README.markdown,
          yarn.lock,
          gulpfile.js
         ]
include: [
          .htaccess
         ]

navbar: true

permalink: pretty
