# Basic settings
name: Jonathan Poltak Samosir's Blog
timezone: Asia/Jakarta
encoding: utf-8

assets:
  assets:
    - "styles.scss"
    - "syntax-theme.css"
    - "jekyll-theme.css"

gems:
  - jekyll-assets

# Conversion
markdown: kramdown
highlighter: rouge

# Serving
detach: false
port: 4000
host: 127.0.0.1
incremental: true

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "posts"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "pages"

exclude: [
          docs/,
          lib/,
          scripts/,
          search.json
         ]
include: [
          .htaccess
         ]

navbar: true

permalink: pretty
